### ISSUE TITLE
Handle containers changing

### ISSUE THREAD

**Issue by jonathanKingston** [kintesh/containerise#1]
Relying on container name is a little fragile and will require you to monitor for these changes in case people change their containers.

Personally I would be storing cookieStoreId in the format and allow the user to change the name which you can update whenever they click the browser action.

We now support in 57 onRemoved, onCreated and onUpdated to check for when containers are removed you likely will either want to use these or browser.contextualIdentities.get(cookieStoreId) before changing the tab in the code.

Check hacks.mozilla.org tomorrow as we are releasing a post about the latest container changes.

**Comment by kintesh** [comment]
@jonathanKingston Thanks for your suggestion. My original plan was to use cookie store id but I opted for a simple option to start with as I wanted to learn more about writing web extensions in general. I'll be making switching to cookie store id with new UI to make it easier to add new entries. Also context menu is something I am thinking of too.

**Comment by jonathanKingston** [comment]
Cool let me know if you have questions, I know we got a lot of users asking for this as a feature so it's great you have started in this direction.

**Comment by kintesh** [comment]
Feature added and released in v2.0.0
