### ISSUE TITLE
Browsing sites bound to No Container open up in new tabs

### ISSUE THREAD

**Issue by Nepherte** [kintesh/containerise#102]
As of version 3.5.0, when browsing sites that are bound to "No Container", will open up a new tab every time instead of staying within that tab.

E.g. github.com as the only rule stored under No Domain. Going from one github page to the other, triggers the creation of a new tab every time (and closes the old tab if configured it as such under settings). Browsing sites for which no rule exist (not even for "No Container"), still works as expected.

**Comment by LoveIsGrief** [comment]
I can't reproduce your issue. 

Could you post a the relevant rules and a screenshot of your settings? Have you activated default containers?

**Comment by Nepherte** [comment]
Settings:
<img width="516" alt="Screenshot 2019-10-09 at 22 48 52" src="https://user-images.githubusercontent.com/55176/66492434-fc6eac80-eae6-11e9-97c6-38e6d7b6d970.png">

Rules:
`github.com , No Container`

Steps to reproduce:
1. Open github.com
2. Click on 'Enterprise' in the link
=> Actual: the current tab gets closed, a new tab opens with the new url
=> Expected: new url opens in the active tab

**Comment by LoveIsGrief** [comment]
Thanks for the step! I was able to reproduce it.

**Comment by OdinGitDat** [comment]
Can this fix be pushed to release asap? I've been waiting to update since #89

**Comment by kintesh** [comment]
@OdinGitDat just released!
