### ISSUE TITLE
Provide an option to use No Container as the default container

### ISSUE THREAD

**Issue by Nepherte** [kintesh/containerise#106]
Note: More a feature request than anything else.

Before v3.5 I've specified a bunch of rules for frequently visited sites to break out of an existing container and fall back to "No Container". What I truly intended is for any site that doesn't have a rule, to break out of a container.

Starting with v3.5 I can use the "Default Container" option to break out of any other container if the domain doesn't match any specified rule (which is great).

What would be even more awesome is if I could repurpose "No Container" as the "Default Container". Why? Whenever I want to branch out of whatever it is I'm doing in the current tab, to open up a new tab, which in turn loads the home page configured in Firefox (in my case a search engine). This home page is not matched by any rule, which would trigger the deletion of the tab and re-opening the page in the default container. 

I'm probably nitpicking here (I acknowledge that other user's browsing patterns may differ), but this saves me a couple seconds each time I open up a new tab. For sure, there may be another add-on that allows me to open tabs in a specific container (the default one), but this sounds like a nice addition to Containerise.

**Comment by LoveIsGrief** [comment]
You are able to use "No Container" as the default container. Just use that name in the preferences.

I'll need to add a user documentation page on default containers. But if the above doesn't solve your problem could you have a look at [this](https://github.com/kintesh/containerise/pull/91) for now and see if variables solve your problem.

You can easily use "{host}" as the name of the default container, make it temporary and add a default rule of `@^https://(www\.)?{domain}\.{tld}`.

**Comment by Nepherte** [comment]
Using "No Container" seems to work for me, so that's exactly what I was asking for :) It wasn't very clear from a ui perspective though (of lesser importance to me).

**Comment by sojusnik** [comment]
> I'll need to add a user documentation page on default containers.

Would really appreciate that, because it's still not mentioned in the documentation when clicking on the question mark to the right of "default container" in the add-on's settings.

**Comment by LoveIsGrief** [comment]
PR welcome. I won't be able to get around to this for a while
