### ISSUE TITLE
Regex broken

### ISSUE THREAD

**Issue by p-rintz** [kintesh/containerise#111]
Hello,

regex support seems completely broken for me.
Even the most simple:
`.?example.com , Test`
does not work.
The tabs are not being loaded in the containers that I specified.

The example regex in the readme also does not work.
`@.+\.amazon\.co\.uk$, Shopping`
Tested in Firefox 69 and 70, with all other addons disabled and also with only Containerise, Temporary Containers and MAC enabled.

OS: Linux

If you need any further logs etc, please do not hesitate.

I definitely think Im doing something wrong, but I am rather confused as to what is causing this.

**Comment by LoveIsGrief** [comment]
Hi,

Have you prefixed your expression with @?

**Comment by p-rintz** [comment]
I copied the regex from the example verbatim, so including the @ as well.

It just started working again though as I tried again. Im honestly rather confused why it didnt work before. I didnt really change anything concerning containers in the last hours.

Guess this can be closed.
