### ISSUE TITLE
Sites assigned to “No Container” open in different container

### ISSUE THREAD

**Issue by mrtootoo** [kintesh/containerise#115]
I am not sure if this is a bug or configuration issue.  I also have “Temporary Containers” enabled.  The sites I have assigned to “No Container” open in the current container vice “No Container”.  I don't recall having this issue when I first configured Containerise.  I do not have this issue with my other sites assigned to named containers.

**Comment by LoveIsGrief** [comment]
Sorry for the late answer, but I assume you're still experiencing the issue. Could you provide more information in order for me to recreate it? These would be necessary:

 - the affected rules
 - a screenshot of your settings

**Comment by mrtootoo** [comment]
Thanks for responding.  I have not experienced this issue lately.

**Comment by LoveIsGrief** [comment]
Alright, then I'll close this issue for now.

Have a nice Sunday.
