### ISSUE TITLE
Doesn't redirect rules before main domain when match domain option enabled

### ISSUE THREAD

**Issue by sungerbob** [kintesh/containerise#116]
Hey, @LoveIsGrief thank you for adding "Match domain" option. 
It doesn't redirects with Match domain option when following rules set.
```
www.github.com
!*.github.com
```
I mean any rules that set before main domain didn't redirect. I can fix it with changing rules to
```
github.com
!*github*
https://github.com
```
Here's a gif that I recorded.
![1233](https://user-images.githubusercontent.com/31207969/71783867-c0af8a00-2fe4-11ea-8dee-cb536032c334.gif)

It doesn't big problem for me, I just want to share what I found. Thank you for adding "Match domain" option, it's very useful for me.
Best regards.

**Comment by LoveIsGrief** [comment]
Hi,

Could you please post all your rules? I see you created the "Default Container" container which is being used when "Match domain" is activated.

Thanks for taking the time to report the issue and for the gif!  :slightly_smiling_face:

**Comment by sungerbob** [comment]
Hi, thank you for your kindness :)
I tried with following rules for gif. Other containers (google, reddit, etc.) is empty.
```
!*.github.* , Github
!*.github.com , Github
```

**Comment by sungerbob** [comment]
Actually you can use 

> !github* , Github

Rule to fix this issue @LoveIsGrief 

Btw, I saw your repo. I hope your effort will be merged soon 😊
