### ISSUE TITLE
Question: paying via Paypal behaviour

### ISSUE THREAD

**Issue by stueja** [kintesh/containerise#118]
First off, thank you very much for this extension. It gives me a good feeling of who can see my cookies etc.

I had a bill to pay via Paypal. The billing website was in the "Personal" container, the Paypal website in configured to open in the "Shopping" container.

When I clicked on the Paypal link in the Personal container, Paypal opened in the Shopping container. This is, as far as I understand the extension, the exact desired behaviour.

But, no payment details or even the fact that I had to pay a bill was transferred. So the only thing I could do is login, but not pay the bill. I am aware of the fact that also this is desired behaviour.

How can I nevertheless pay bills via Paypal?

Thanks alot.

**Comment by LoveIsGrief** [comment]
For things like these, I just use private windows as a workaround.

I believe this can be fixed when #53 is implemented and such, it's a duplicate.
