### ISSUE TITLE
Containerise ignores browser.tabs.loadDivertedInBackground

### ISSUE THREAD

**Issue by practik** [kintesh/containerise#12]
### STR:

- In about:preferences, make sure you have at least two containers set up (I'll call them A and B).
- In about:config, set browser.link.open_newwindow.restriction to 0 and browser.tabs.loadDivertedInBackground to true.
- From the Containerise menu, add `github.com` to the list for Container A and `kinte.sh` to the list for Container B.
- From `https://github.com/kintesh`, middle-click (or Ctrl+click on Windows / Cmd+click on Mac) on the link to the Containerise repository. The link will open in a new tab in the background. This is the expected behavior.
- Now middle-click on the link to `http://kinte.sh`. The link will open in a new tab, **and** the browser imediately focuses on that tab. This is not the expected behavior.

**Comment by kintesh** [comment]
Released with 2.3.0

**Comment by practik** [comment]
It seems to be working perfectly now. Thank you, @kintesh!
