### ISSUE TITLE
Syntax to Assign Multiple Domains to Same Container?

### ISSUE THREAD

**Issue by CrafterLaughter** [kintesh/containerise#121]
Forgive my ignorance.  I daily use a site that uses single sign on and its control panel page is on a separate domain from its primary domain.  Is this possible?  If so, what is the correct syntax?

I tried the following thus far without success.

!*.domain1.com, !*.domain2.com , UniqueSingleSignOnContainerXYZ
!*.domain1.com,!*.domain2.com , UniqueSingleSignOnContainerXYZ
!*.domain1.com; !*.domain2.com , UniqueSingleSignOnContainerXYZ
!*.domain1.com;!*.domain2.com , UniqueSingleSignOnContainerXYZ

edit: clarify uniqueness of container name

**Comment by LoveIsGrief** [comment]
Hmm.. don't you have the ![icon](https://github.com/kintesh/containerise/blob/master/static/icons/icon.png) ? If you click on it, you won't need to edit the lines. Just click on the "+" and add the other website.

**Comment by CrafterLaughter** [comment]
@LoveIsGrief  Your suggestion helped me think differently.  Many thanks.

I had been just using containerise by always using the CSV editor but then realized the container dropdown in the top of the GUI which reminded me that's one way multiple domains could be added to the same container that way.

That made me realize I just need to use the same syntax in the CSV file but just make a point of referencing the same container name when adding multiple domains.  I was foolishly thinking multiple domains linked to the same container would be noted on the same line.  So it's as simple as follows on multiple lines.

E.G.
!.google.com.com , GoogleSingleSignOnContainer
!.gmail.com , GoogleSingleSignOnContainer
!.youtube.com , GoogleSingleSignOnContainer

@LoveIsGrief   @kintesh   Thanks for all amazing contributions you guys have made to this extension!

**Comment by LoveIsGrief** [comment]
I'm glad you figured it out :+1: 

Have a nice day :slightly_smiling_face:
