### ISSUE TITLE
Matching more than just host/domain?

### ISSUE THREAD

**Issue by junkblocker** [kintesh/containerise#127]
A rule of 

```
!*.gov, gov
```

makes

```
https://forklog.media/safety-over-freedom-how-governments-introduce-surveillance-under-veil-of-coronavirus-control/
```

match the `gov` container.

**Comment by LoveIsGrief** [comment]
Have you tried setting the "Match domain only" preference?
![preference](https://user-images.githubusercontent.com/2829538/79071032-a23ee600-7cd9-11ea-8fb0-440a5ea44c00.png)

**Comment by junkblocker** [comment]
That works. I'd say that should be the default since every other tools in the world works like that. But anyway, maybe the examples should also make it clearer that it is not the default as all rules shown only operate in domain matching mode.
