### ISSUE TITLE
Feature request: don't replace the existing tab when changing containers

### ISSUE THREAD

**Issue by parkerault** [kintesh/containerise#14]
When a navigation event triggers a container change, the current tab is replaced with a new one and `window.history` is lost. This is kind of frustrating when I'm opening links from a search results page and I can't go back. Is it possible to always open a new tab if the new location is assigned to a different container?

**Comment by stoically** [comment]
Changing the container of a existing tab is [not yet](https://github.com/mozilla/multi-account-containers/issues/1029) possible. A possible workaround might be to open a completely new tab and leave the old one open when a requests triggers a container change (multi-account containers does that too).

**Comment by parkerault** [comment]
I didn't phrase it clearly, but that's what I was trying to say in the last sentence of my previous post. I definitely think keeping the old tab open vastly better UX.

**Comment by kintesh** [comment]
Released with 2.3.0

**Comment by quietlystorming** [comment]
It seems this is happening for me now. I'm using version 3.0.1, and when I navigate to a container-defined URL, a new tab closes and replaces the current one. Using FF 66.0.3, win8.1 x64, tested with all other add-ons disabled.

**Comment by ashwinvis** [comment]
I can confirm that the issue persists, I start searching, click on a website assigned to a container, now I cannot press the back button. The official container extension does not have the problem.

**Comment by PopeRigby** [comment]
It's [happening](https://open.tube/videos/watch/1e2c1747-7edc-40a1-801f-a8a790575622) to me too. Can you re-open this issue @kintesh?

**Comment by Drulac** [comment]
Hello,
I can confirm that the issue persists, is there any workaround here :smiley: ?
