### ISSUE TITLE
*.example.com match both domain and subdomain

### ISSUE THREAD

**Issue by Myuki** [kintesh/containerise#157]
I find `*.example.com` can match both `example.com` and `www.example.com`.

But I can't find any description in `README.md`. Is it an intentional design? If it is. It is better to add some descriptions in `README.md`.

**Comment by geeknik** [comment]
This information is available in the extensions documentation: `moz-extension://55655d9f-8497-4f8c-a96b-c6dd308f195b/docs/ui-preferences/default_containers.html`. 

![2021-07-18_10-22](https://user-images.githubusercontent.com/466878/126072773-580ea594-3ba4-40d0-a970-1e8b1e688da2.png)
