### ISSUE TITLE
Discord site tries to exit the container, causing a loop of creating tabs

### ISSUE THREAD

**Issue by xcasxcursex** [kintesh/containerise#168]
I have these rules in place:

*.discord.com , Discord
*.discordapp.com , Discord
*.discordapp.net , Discord

They've all worked in the past. Recently, if I clicked a link pointing to discord's servers, it would enter an endless loop of opening a new tab, closing the current one, repeat.... I disabled containerise, opened a new tab in the Discord container, typed in the URL (discordapp.com) manually, and it opened a new tab outside of the container. I guess with containerise in place, discord is not allowed to open in the default container, and it won't allow to open outside of it, so it loops.

I don't think this is a containerise bug, it may be a firefox bug I'm unsure (I don't think discord should be allowed to break out of its container?), but basically, it's discord being shady as usual, and the result is an unresponsive browser.

**Comment by crssi** [comment]
For sure you need to add `discord.com , Discord` for `discord.com` ro be opened in `Discord` container.

**Comment by xcasxcursex** [comment]
> For sure you need to add `discord.com , Discord` for `discord.com` to be opened in `Discord` container.

The rule is in place and working, discord tabs are opened in the discord container, but the website then opens itself in a new tab in no container.

...Which is forced by containerise, to open in a Discord container tab
...but the website then opens itself in a new tab in no container.
...Which is forced by containerise, to open in a Discord container tab
...but the website then opens itself in a new tab in no container.
...Which is forced by containerise, to open in a Discord container tab
...but the website then opens itself in a new tab in no container.

....This goes on forever.

**Comment by xcasxcursex** [comment]
I've managed to track this down. Somehow, this setting was enabled. 

![image](https://user-images.githubusercontent.com/58130821/145567567-c417a24f-877c-4825-9ce1-a0766494096b.png)

It wasn't me, I didn't even know this setting existed until I traced it just now. I'll close this case but hopefully it might help if this behaviour crops up again, which I get a funny feeling it will.....
