### ISSUE TITLE
API to check whether an URL is assigned

### ISSUE THREAD

**Issue by stoically** [kintesh/containerise#17]
Hi,

@shvchk asked if it would be possible to support your Add-on in combination with mine here: https://github.com/stoically/firefox-add-on-temporary-containers/issues/15

For that to work properly I'd need an API to ask your Add-on whether a specific URL is assigned. Here's how Multi-Account Containers is doing it: https://github.com/mozilla/multi-account-containers/issues/1130#issuecomment-368030620

Would you be up to implement something like that or accept Pull requests implementing it?

Best regards

**Comment by kintesh** [comment]
I am heppy for you to create a PR.

**Comment by stoically** [comment]
Before I start working on this it would be good to know in what way you would want to see it implemented. It would require adding [`runtime.onMessageExternal`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessageExternal) - now the question is, who should be able to get an answer? The options I see are:

* Adding the `management` permission and checking for `contextualIdentities` permission
* Adding a whitelist that has to be manually maintained
* Just answering whoever asks

**Comment by kintesh** [comment]
I think it best to lock it down to specific id and manually maintaining it. The way I see it is that this extentions won't change much from what it is now.

**Comment by shvchk** [comment]
Just wanted to thank @stoically and @kintesh for working on this and container stuff in general. You guys are awesome! :metal:

**Comment by innir** [comment]
@kintesh Would you mind releasing a new version? Currently I can't use containerise because of this.
BTW: Thanks for your extension, it is really the last missing piece to get a smooth container experience.
