### ISSUE TITLE
Possible to match the equivalent of "*google.com/maps*"?

### ISSUE THREAD

**Issue by RandomNerd1** [kintesh/containerise#179]
maps.google.com works perfectly, but some links to Google Maps are also in the format of google.com/maps/(stuff), and it doesn't seem like I can get Containerise to put Google Maps into the container when the URL is structured that way, without having it 'catch' every single google site/service/etc.

Is there any way to do this? Thanks in advance!

**Comment by offhub** [comment]
Containerise > Options\Preferences > Disable 'Match domain only'

```
@^https?:\/\/(((www\.|)google\.[a-z.]+\/maps)|(maps?\.google\.[a-z.]+))(|\/.*)$
```

**Comment by RandomNerd1** [comment]
This seems to be working perfectly, thanks so much! I never would have figured that out, lol
