### ISSUE TITLE
non-containment (prevention, for some addresses or types of address)

### ISSUE THREAD

**Issue by grahamperrin** [kintesh/containerise#2]
Might this become an option? 

Please compare with: 

- ["Open always in no container" setting · Issue #503 · mozilla/multi-account-containers](https://github.com/mozilla/multi-account-containers/issues/503)

– with (from me): 

> … I imagine that in a majority of cases, it will be sane to _enforce_ non-containment of `about:` … URLs.

**Comment by kintesh** [comment]
For the next itteration I am planning to have better ui with dropdown options to pick container. I guees `No container` could be an option to pick. I also want to an option to export/import json based configuration.

**Comment by kintesh** [comment]
Alternatively, you could have scrict container mapping where vising a site (not mapped to any container) from a container should open that site without any container.

**Comment by grahamperrin** [comment]
> … vising a site (not mapped to any container) from a container should open that site without any container. …

I like that idea. If implemented, it should probably be a user preference. 

Planning for possible futures: consider Mozilla bug [1323873 - Allow tabs to change user contexts when navigating](https://bugzilla.mozilla.org/show_bug.cgi?id=1323873) in the context of: 

1. some users' wishes to view no more than one container at a time; and 
2. (a flip-side) some users' wishes to **view nothing contained whilst viewing anything that is non-contained**. 

Point (1) is within recent discussions at and around https://discourse.mozilla.org/t/-/15331/4?u=grahamperrin

From a Containerise development perspective, consider how the UI to the extension should behave _if_ the action of mapping, by a user, will causes what's mapped to disappear from the window.

**Comment by testsubject33** [comment]
Hi, I think having a no container option to choose would be great

**Comment by kintesh** [comment]
Feature added and released in v2.0.0
