### ISSUE TITLE
[Feature request] Support regex

### ISSUE THREAD

**Issue by malore** [kintesh/containerise#21]
It would allow much more flexibility.

**Comment by ethhics** [comment]
Unless I'm missing something, there aren't any use cases for full fledged regex implementation. Could you provide some examples of when and how it would be used?

**Comment by malore** [comment]
Effectively, it would be sufficient for me to support wildcards for TLDs(e.g. google.*), but supporting regex - and full URLs - will allow to open all searches with a specific item in a specific container (e.g. google\.com/\.*q=news, News).

**Comment by rmenessec** [comment]
It would match port numbers, too.

I've spent a lot of time stuck on intranets where several web sites are running off a single server—or at least a single hostname or IP—which are only differentiated by port number or path elements (or both). Underneath the one host name, there may be multiple servers or multiple webserver services on the same host; none of which share data. (See also proxies provided by Apache httpd / nginx / IIS, _etc._)

Full regex support would be very handy. It seems like the cleanest way to write rules that can match subdomains, port numbers, and other URL elements. It might even be necessary to match protocols at some point (HTTP vs. HTTPS).

**Comment by elypter** [comment]
you could have different reddit accounts for different subreddits or different forum accounts for different subforums or you could appear logged in to a website only if you want to. eg: when writing comments or viewing the profile page.

**Comment by matt2hews** [comment]
Providing support for wildcards such as *.google.com would be helpful enough, even if it weren't full regex.  Currently, each subdomain has to be listed individually to have it function as desired.

**Comment by rmenessec** [comment]
Seconding @matt2hews. If the delay in implementing this badly-needed functionality has anything to do with the complexity of regex, I'd gladly settle for simple wildcard functionality; at least to begin with.

**Comment by businessBoris** [comment]
> Unless I'm missing something, there aren't any use cases for full fledged regex implementation. Could you provide some examples of when and how it would be used?

Please see firefox add-on called "cookie autodelete" for a very good demonstration of regex and wild cards (to an extent). 

I would like regex support so that I can direct (www|alerts|contacts|maps).google.(co.uk|com) and others to a "tracking" container and console.cloud.google.com to a "company" container (because they use two different google accounts). Without regex that would be a great big list to manage in each container list for your add-on.

**Comment by LoveIsGrief** [comment]
I would like to start work on this.

Multiple options:


# Treat all entries as regex

Less flexible and would force to introduce a new way of handling globs (should that ever be requested)

# Add preference on how to treat all entries by default

More flexible, but still a global setting. At least it will be possible to add more options e.g

 - treat as normal string
 - treat as glob
 - treat as regex

# Introduce prefixes to allow special treatment on case by case basis

We would need to define the prefixes I propose:

 - no prefix --> normal treatment
 - `#` --> glob
 - `@` --> regex

Examples:

 - `google.com` --> only `google.com` is containerised
 - `#*.google.com` --> treat as glob (`*.google.com`)
 - `@.+\.google\.com$` --> treat as regex `.+\.google\.com$`

------------------

Thoughts?

**Comment by businessBoris** [comment]
@LoveIsGrief Good luck sir(?)!
If you have the time to create another profile for Firefox and install https://addons.mozilla.org/en-GB/firefox/addon/cookie-autodelete/ you can see that the glob to regex conversion is visible and quite ingeniously presented. You shouldn't need the prefixes.
Happy to help in any way that I can.

**Comment by LoveIsGrief** [comment]
@businessBoris I had a look at cookie-autodelete, do you mean [this](https://addons.cdn.mozilla.net/user-media/previews/full/189/189658.png?modified=1543520769) ? It looks like auto-converstion glob -> regex. One can only edit the glob and not the regex.

If one were able to edit the regex, on wouldn't be able to convert any regex to glob, so I don't think I'll be going for that.

Or have I misunderstood how it works?
