### ISSUE TITLE
Cyberfox 52.7.2 (64-bit)

### ISSUE THREAD

**Issue by sutex** [kintesh/containerise#23]
Cyberfox 52.7.2 (64-bit) no icons showing and nothing can be saved. 
https://i.imgur.com/ccajHYR.png
the grey bar you can see just keeps sliding along.

Please keep 'us' alternative users in mind , I can use my unsigned plugins in Cyberfox

**Comment by kintesh** [comment]
Hi, I cannot test it myself as I devlope on Mac OS X and haven't got around setting up Linux enviroment. Feel free to create a PR if you manage to fix this before I do. Thanks!.

**Comment by LoveIsGrief** [comment]
@sutex has anything improved? Are you still using Cyberfox?

**Comment by sutex** [comment]
@LoveIsGrief  No moved on Waterfox  Cyberfox stopped been developed so not using this addon

**Comment by LoveIsGrief** [comment]
I guess that settles it.
