### ISSUE TITLE
Open in background

### ISSUE THREAD

**Issue by Zorroblanco** [kintesh/containerise#26]
Hi,  great addon!, but please add option to open containers in background, it s a problem than always open in forward. Firefox 59.0.2 32 bit,  browser.tabs.loadDivertedInBackground: true win 7 x86. (for example with extension "Temporary Containers by stoically", no problem with open in background) Sorry for my english I hope you can understand.
Cheers

**Comment by olliebean** [comment]
This is the one thing that's preventing me from switching to this addon from the official one. I need to be able to middle-click links and not have the new tab suddenly switch to the foreground because it's opened in a different container.

**Comment by ethhics** [comment]
> I need to be able to middle-click links and not have the new tab
> suddenly switch to the foreground because it's opened in a different
> container.


@Kintesh, I believe that this is fixible by simply adding `active: false` after `webRequestListener.js:10` as per [`tabs.create()`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create).

**Comment by kintesh** [comment]
Released with 2.3.0
