### ISSUE TITLE
Containerise does not respect the selected tab

### ISSUE THREAD

**Issue by andreicristianpetcu** [kintesh/containerise#28]
I have mozilla.org mapped to my personal container.
![screenshot from 2018-04-20 18-50-02](https://user-images.githubusercontent.com/922368/39063598-e9a7e3cc-44cb-11e8-8a9f-1f5a2605abe6.png)

If I open a mozilla.org page from some [non-mapped page like DuckDuckGo](https://duckduckgo.com/?q=bugzilla+main+page&t=ffab) with ctrl+click it will auto select the next page. https://vimeo.com/265791931

I expect the search page to still be selected.

**Comment by andreicristianpetcu** [comment]
I sent a PR to fix this https://github.com/kintesh/containerise/pull/29

**Comment by kintesh** [comment]
Thanks for PR. Released with 2.3.0
