### ISSUE TITLE
[feature request] Allow Wildcarding

### ISSUE THREAD

**Issue by draggehn** [kintesh/containerise#3]
Example use case: send all Google domains to a specified container (play.google.com, inbox.google.com, mail.google.com, etc) by inputting "*.google.com , Google"

Is this possible with the current state of containers?

**Comment by kintesh** [comment]
In next release.

**Comment by kintesh** [comment]
Looks bit complicated, I'll look at it later.

**Comment by kintesh** [comment]
Feature added and released in v2.1.0
