### ISSUE TITLE
[feature suggestion] add button to add current website

### ISSUE THREAD

**Issue by elypter** [kintesh/containerise#31]
when managing the domains of a container there should be a button to easily add the domain of the website in the active tab.

**Comment by kintesh** [comment]
I am thinking of having a context menu.

**Comment by elypter** [comment]
those get cluttered though and are difficult to access on mobile

**Comment by LoveIsGrief** [comment]
@elypter what exactly is the button supposed to do? And where is the button supposed to be added if you don't want a context menu? Extensions are limited to a single button, but there are no limitations on the number of contextmenu entries.

**Comment by doronbehar** [comment]
Currently what is implemented is a context menu right? I think a configurable keyboard shortcut should satisfy @elypter.

**Comment by LoveIsGrief** [comment]
I think this has been resolved simultaneously with #39 

I'd be inclined to close this unless a more detailed feature description is provided
