### ISSUE TITLE
Autofill with current URL when adding a new rule

### ISSUE THREAD

**Issue by edouard-lopez** [kintesh/containerise#39]
Hi, nice addon!

On my first use, I was expecting the _add new rule_ feature to suggest the current URL or FQDN I was visiting.
This will reduce friction for users.

**Comment by ethhics** [comment]
Similar to #31, though I like this idea more

**Comment by LoveIsGrief** [comment]
Seems easy and reasonable enough. I think FQDN is best.

Drafting a pull request...
