### ISSUE TITLE
Request: allow containerising at deeper level than hostname

### ISSUE THREAD

**Issue by klint** [kintesh/containerise#4]
It would be useful to be able to assign a container at a deeper level than hostname.
For instance, at parameters level, with Google Group as a use case.
I would like to open the 2 following groups (who belong to 2 different google accounts) in 2 different containers automatically:
https://groups.google.com/forum/?fromgroups#!managemembers/**_groupename1_**/members/active
https://groups.google.com/forum/?fromgroups#!managemembers/**_groupename2_**/members/active

Not sure where I should send the request to: Containerise addon, or Multi Container addon... :) 
Thanks

**Comment by eberhardweber** [comment]
I actually expected this add-on to do exactly that! I would be especially interested in subdomain and subfolder support, i.e., for example: np.reddit.com and reddit.com/r/subreddit/.

**Comment by ethhics** [comment]
This is fixed by #5, though this version is not on the add-on site yet.

**Comment by kintesh** [comment]
I was making few changes yesterday. Will publish it later today.

**Comment by klint** [comment]
has the subfolder part been implemented already? If so, how would I associate different containers to the examples URLs below?
https://groups.google.com/forum/?fromgroups#!managemembers/**_groupename1_**/members/active
https://groups.google.com/forum/?fromgroups#!managemembers/**_groupename2_**/members/active
Thanks :)

**Comment by kintesh** [comment]
This kinda works with v2.5.0 but its case sensitive. I'll fix this in next release.

**Comment by kintesh** [comment]
Fixed in 2.5.1.
