### ISSUE TITLE
strict_min_version 57.0

### ISSUE THREAD

**Issue by grahamperrin** [kintesh/containerise#42]
Follow-up to https://github.com/kintesh/containerise/commit/84cb6415989e8aa2994c5b2c188d8fea8016f938#commitcomment-29214740

Versions 2.4.0 and 2.5.0 do seem to work (at a glance) with Waterfox 56.2.3, which falls below the strict minimum version. Also, at <https://addons.mozilla.org/addon/containerise/versions/>: 

> Works with Firefox for Android 57.0 and later, Firefox 57.0 and later 

Please, should I be aware of any _particular_ risk/problem when mixing 2.5.0 with Waterfox 56.2.3?

**Comment by kintesh** [comment]
Changed to 53 in v2.5.1.

**Comment by grahamperrin** [comment]
https://github.com/kintesh/containerise/commit/15f1597304be51bb08a792cd0f495f153c783a01 noted with thanks, in particular: 

> … 53. (Some functionality may not work). …
