### ISSUE TITLE
Catch keyword-based searches

### ISSUE THREAD

**Issue by Reylak** [kintesh/containerise#43]
When using a [smart keyword](https://support.mozilla.org/en-US/kb/how-search-from-address-bar?redirectlocale=en-US&redirectslug=Smart+keywords) in the location bar to do a search, the used tab is not moved to the corresponding container, even if the tab is not in any container (I understand the behavior is expected if the tab is already in a container, as the container change also does not happen during normal navigation).

**Comment by Reylak** [comment]
I just realized it actually catches keyword searches, but only when there are two words in the search! For instance, with the search keyword "kw": "kw test" is **not caught**, but "kw double test" is caught.

**Comment by LoveIsGrief** [comment]
I'm not observing this behavior and use keywords quite regularly. Could you give an example:

 - URL and keyword
 - containerise rule

**Comment by Reylak** [comment]
The website is https://www.gamekult.com/. I set the keyword `gk` for the search in the main search bar you see at the top. Containerise rule is simply `*.gamekult.com`.

The thing is, visiting this website from a clean tab **does not put the tab in the container**, as if the rule was not triggered. Refreshing the page with F5 does not fix this behavior, however **refreshing without the cache with Ctrl+F5** successfully triggers the rule, and the tab is moved to the dedicated container.

**Comment by LoveIsGrief** [comment]
😮 I'll be damned, I reproduce it with `gk test`.

Thanks for the bug report @Reylak ! I'll get on this when I have time

**Comment by kintesh** [comment]
This should be closed. @Reylak Can you please check if everything is working as expected?

**Comment by Reylak** [comment]
Nice work, it works as expected on this website. Nice catch of this corner case, thank you!
