### ISSUE TITLE
[Feature request] Add preference to choose matching hostname or complete URL

### ISSUE THREAD

**Issue by LoveIsGrief** [kintesh/containerise#44]
#4 Added matching the path component of the URL, which is not in the addon description and something I discovered while looking at the code.

I think it would be good to define in a preferences page whether the complete path or just the hostname should be considered for matching. The reason is partially because of #21 (regex support) which will make regexes like `(yada|pop)\.somewhere\.test$` fail for urls like https://pop.somewhere.test/this/is/a/path .

**Comment by lucassz** [comment]
I support this as well. I noticed this issue when using globs, where something like `*://*.amazon.com/*` will also match addresses on a completely different domain that have an Amazon link without a query parameter. I can fix this with a more elaborate regex, but it makes the globs pretty much unusable.
