### ISSUE TITLE
Addon does not work anymore... 

### ISSUE THREAD

**Issue by klint** [kintesh/containerise#6]
Strange!
The addon has stopped working for me (I even tried going back to 2.0). 
Still using last FF57 beta, but in the meantime I have added a lot of other addons. Could there be a conflict?
Nothing shows up in the error console.
Thanks

**Comment by kintesh** [comment]
I've just tested it in FF57 and it works find for me. So it looks like it could be one of your other addon.

**Comment by klint** [comment]
I have deactivated all addons but Containerise and the Multi Accounts one in Firefox 57 Beta 14
My Containerise setting contains the following:
https://groups.google.com/forum/#!forum/ahqg_info , AHQG
http://ahqg.free.fr/ahqgv2/html/accueil.php , Personnel
But it still does not work for any of the 2 above URLs. 
Is the syntax wrong?
Thanks

**Comment by kintesh** [comment]
@klint it only works with domain and not full urls.

**Comment by klint** [comment]
Stupid me! Sorry for taking your time for that. It works fine now... as before, as always ;)
