### ISSUE TITLE
Redirects specified glob rule whether or not in adress bar

### ISSUE THREAD

**Issue by sungerbob** [kintesh/containerise#64]
I think it shouldn't open specified rule in searches etc. but it should on links. I don't know why it didn't open in google but ddg.

![123](https://user-images.githubusercontent.com/31207969/60045754-4ebdc600-96ce-11e9-81a3-fee5666ff5e7.gif)

**Comment by kintesh** [comment]
Its bit hard to see in the gif. Can you post your rules.

**Comment by LoveIsGrief** [comment]
@sungerbob you have a rule to open google URLs in the google container. I'm not exactly sure how this would be resolved. Maybe by adding precedence, but how? 

Possibly a popup when a URL matches multiple rules.

**Comment by sungerbob** [comment]
@kintesh Just wanted redirect all amazon sites (like .com, .co.uk, .de, .in, etc.) to amazon container.
- !*.amazon*
- !*.amazon.!*

**Comment by LoveIsGrief** [comment]
@sungerbob what about your google rules?

**Comment by sungerbob** [comment]
@LoveIsGrief I don't know how I'm getting this but I'm getting on few websites. Like duckduckgo etc.
`!*.gmail.*`
`!*.google.*`
`!*.youtube.*`

**Comment by sungerbob** [comment]
Looks like it's fixed with "Match domain only" option in addon's preference.

**Comment by sungerbob** [comment]
Yeah, I'm having exactly same problem as you described. I'm looking forward to next release :)
