### ISSUE TITLE
Store hosts under dedicated key in storage

### ISSUE THREAD

**Issue by LoveIsGrief** [kintesh/containerise#66]
In order to introduce preferences, the internal storage structure has to be changed such as #44. It might also help fixing #45

**Comment by kintesh** [comment]
At the same time we can migrate to using sync. Its better to keep one breaking change.

**Comment by LoveIsGrief** [comment]
Honestly, I'd rather have the choice between local and sync storage. A preference would be preferred and this would pave the road for that and future preferences. Plus a finer granularity in the versions would be better:

 - version N: separation of keys in storage
 - version N+1: preference X
 - version N+2: preference Y

That would also allow users to fallback to specific features.
