### ISSUE TITLE
3.1.0 update breaks compatibility with Temporary Containers

### ISSUE THREAD

**Issue by lucassz** [kintesh/containerise#70]
Containerise was coexisting wonderfully with Temporary Containers for me until the 3.1.0 update, but the change to have "all unmapped urls now open outside of any container" seems to have broken the compatibility with TC's Isolation Mode.

**Comment by Radagast** [comment]
I'm not sure the only issue is with temporary Containers. For me, with Containerise alone I get two tabs opening for any link to a site with a defined container. With TC enabled it can be multiple tabs. Unfortunately, TC also got an update today too. That said, reverting to 3.0.1 seems to fix the issue.

**Comment by pezz** [comment]
Is there somewhere I can download the 3.0.1 xpi from until this is fixed?

Cheers.

**Comment by dboy591** [comment]
The breakage with TC seems to be due to the lack of a "No Container" in this latest version of Containerise.  Manually reverting to the previous version for now.

**Comment by kintesh** [comment]
I will revert the last change. Ideally you should only be using one container add-on as you always run into race condition. FYI I personally stopped using any container extension. So when I develop I don't test comparability with other similar extensions.

**Comment by arlavit** [comment]
> 
> 
> I will revert the last change. Ideally you should only be using one container add-on as you always run into race condition.
No way. Every extension has its own features, so one will lose on this.

**Comment by vshl** [comment]
"all unmapped urls now open outside of any container" should be optional. For instance, if I have two twitter accounts: one personal and one work, I cannot manually assign these twitter accounts to 2 different containers like my current usage.

**Comment by tomose** [comment]
> 
> 
> I will revert the last change. Ideally you should only be using one container add-on as you always run into race condition. FYI I personally stopped using any container extension. So when I develop I don't test comparability with other similar extensions.

I'm on Waterfox with no other container addons and experience the issue of blank tabs opening as well. So it may not be an issue totally exclusive to having multiple container addons.

**Comment by kintesh** [comment]
All the changes of v3.1.0 are reverted in v3.2.0
