### ISSUE TITLE
Introduce prefence to leave tabs behind instead of closing them

### ISSUE THREAD

**Issue by Speravir** [kintesh/containerise#71]
The new behaviour [“Do not close tabs when entering/exiting a container.”](https://github.com/kintesh/containerise/commit/bd8dce66cdb59f9a3b15dd28b15c1240e361c50e) introduced in v 3.1.0 is to no purpose for me – or it is buggy. Now totally empty tabs with no content are left behind here, and this I do not need at all. I switched back to v.3.0.1 for now.

Actually automatically moving certain sites into dedicated containers without leaving traces was the reason I installed this addon. So, please, at least make this new feature adjustable.

**Comment by Speravir** [comment]
Addendum, sorry that I did not think of it yesterday: After reading the linked issues I noticed I should have mentioned, that I use additionally the addons Firefox Multiaccount Containers and Context Plus.

**Comment by kintesh** [comment]
Thanks for the suggestion. For now all the changes of v3.1.0 are reverted in v3.2.0.

**Comment by LoveIsGrief** [comment]
Going to start work on this once #76 has been approved and merged
