### ISSUE TITLE
Opening Facebook container causes running uncontrollable blank tabs + any tab in container is blank

### ISSUE THREAD

**Issue by arlavit** [kintesh/containerise#72]
New version 3.1.0 broke everything. I've had to roll back on 3.0.1. Actually I couldn't even open any tab in any container, because they haven't been loading and have been blank at all. Opening a new Facebook container (Mozilla extension) tab caused unlimited opening of blank tabs.
Other extensions I am using: Easy container shortcuts, Facebook container, Firefox Multi-account containers.

**Comment by burillo-se** [comment]
i have this issue as well - any time i try to open any site that's being forced to containerize, it just endlessly opens new tabs without actually reaching to the site.

**Comment by arlavit** [comment]
> 
> 
> i have this issue as well - any time i try to open any site that's being forced to containerize, it just endlessly opens new tabs without actually reaching to the site.

That's why I had to roll back on 3.0.1 and it's better now.

**Comment by kintesh** [comment]
See https://github.com/kintesh/containerise/issues/70#issuecomment-509736333

**Comment by kintesh** [comment]
All the changes of v3.1.0 are reverted in v3.2.0
