### ISSUE TITLE
v3.1.0 breaks multi-account containers altogether

### ISSUE THREAD

**Issue by dr4Ke** [kintesh/containerise#73]
Using the latest firefox, a completely new profile with "Containerise" and "Firefox Multi-Account Containers" (FMAC below) add-ons only, with no rule in "Containerise".

I'm facing two cumulative behaviors:

- Any site pinned to a specific container with FMAC is opened in a new "no container" tab by "Containerise" and FMAC asks me to open it in the right container again.
- If I tell FMAC to remember my choice about this site (open in Personal container), blank tabs keep opening, then FMAC reopens it in the Personal container, then Containerise opens it in a new no container tab, etc.

It keeps going until I disable one of the two add-ons.

I think it is the same cause than for #70, #71 and #72. I opened this new issue because I think it gives an easily reproducible case.

To reproduce:
- new firefox profile
- install FMAC add-on
- open github.com in a new Personal container tab
- tick "always open in Personal" in FMAC menu
- install Containerise add-on
- open github.com in a new tab
- select "Open in Personal Container" when asked by FMAC
- see a new Personal container tab appear with "github.com/" title but remaining blank
- see a new "no container" tab open and FMAC asking again if you want to open it in Personal

If you want to go wild, tick "Remember my decision for this site".

**Comment by benji1304** [comment]
Could this be causing the issue here? 
https://github.com/mozilla/contain-facebook/issues/469

**Comment by bitstreamout** [comment]
I see this also for amazon container open inifinte tabs in loop ... also search in in duckduckgo open two tabs from search engines where the first is a standard tabg and the second is the a personal tab (as I had configured this duckduckgo) .... only the google container works flawless

**Comment by bitstreamout** [comment]
The only workaround is to add some amazon domains to avoid those loops ... seems that "Containerise" fights against "Amazon Container"  ... I guess that this also is the cause for the loop with "Facebook Container" and similar addons ... and as I had already some google domains configured in "Containerise" the fight with "Google Container" does not happen (as long as I do not access an unkown google domain)

**Comment by benji1304** [comment]
Rolling back to a previous version for the moment seems like the easiest workaround

**Comment by gbdlin** [comment]
When rolling back to previous versions, remember to disable automatic updates for this addon.

**Comment by dr4Ke** [comment]
> Could this be causing the issue here?
> [mozilla/contain-facebook#469](https://github.com/mozilla/contain-facebook/issues/469)

Most probably.

**Comment by dr4Ke** [comment]
The issue is that Containerise systematically opens undefined sites in a "No container" tab, while any other add-on tries to open it in a specific container. The most spectacular effect is with add-ons that automatically do so.

**Comment by kintesh** [comment]
See https://github.com/kintesh/containerise/issues/70#issuecomment-509736333

**Comment by Nnidyu** [comment]
Actually, the comment in #70 is irrelevant here. The change caused problems for me with the following scenarios:

- Using two containers (with no domains mapped) for work and private stuff on Google Drive.
- Using a service that redirects to another domain for login (the another domain cannot be mapped to the service container because it is shared between various services and I am using different accounts with them).

So no interaction with other extensions was involved.

**Comment by stoically** [comment]
The change mentioned in the linked comment is about no longer allowing any url to load in any permanent container that isn't assigned with containerise - also causing your issues.

**Comment by kintesh** [comment]
All the changes of v3.1.0 are reverted in v3.2.0

**Comment by Drizzt321** [comment]
@kintesh I've got v3.2.0 installed and it's opening up infinite new tabs. Although if I close the newest one to open it stops the opening and I can close them all, or if I close the window.

**Comment by LoveIsGrief** [comment]
@Drizzt321 Could you open a new bug for that and describe what you're doing? I can't observe this behavior here
