### ISSUE TITLE
[feature suggestion] automaticially create & assign a container for a domain not already added

### ISSUE THREAD

**Issue by dxlr8r** [kintesh/containerise#80]
Just stumbled a cross this gem. As the subject says, if the domain isn't already added to a container, create a new container with the name of the domain and add the domain to that container.

**Comment by LoveIsGrief** [comment]
I wouldn't use the feature, but sure why not. I believe it should be a setting though and not default behavior. That would make it dependent on #76 and future development to introduce settings

**Comment by dxlr8r** [comment]
Awesome!

**Comment by LoveIsGrief** [comment]
Oh, a question before I get on this @dxlr8r, are you assuming the created container will be destroyed or do you want it to persist?

**Comment by dxlr8r** [comment]
Good question @LoveIsGrief . I guess it would be ok to destroy them, if no page with that url is no longer open, and if it doesn't have any customisation (added domains, etc.).

**Comment by LoveIsGrief** [comment]
OK, that makes it quite similar to a temporary container. And another question: what do you expect of subdomains? 

For example should `google.com` create a `google.com` container and `mail.google.com` create another? Or should they both resolve to `google.com` and end up in the same container?

**Comment by dxlr8r** [comment]
> And another question: what do you expect of subdomains?

Good question. Maybe have that as an option? Personally I think I'd like to have subdomain under the same temporary container as the top domain.

**Comment by LoveIsGrief** [comment]
OK, I'll have to check how to implement that :) I believe I have all the information now. Should you have more precise thoughts on the matter, Don't hesitate to utter them :slightly_smiling_face: Thanks for the responses.
