### ISSUE TITLE
CSV editor wipes all entries when saved input is unmodified

### ISSUE THREAD

**Issue by barneycg** [kintesh/containerise#84]
Latest version (3.3.0 I believe) if you hit save on the CSV editor it wipes it resulting in the loss of all rules configured.

I've reverted to 3.2.0 and all is working as expected again

**Comment by LoveIsGrief** [comment]
I'm sorry, but I can't recreate the issue using the current containerise version. Would you be willing to share the CSV values?

**Comment by barneycg** [comment]
I've repeated this on a different machine with a different list of sites. 
open the csv editor using the pen in top right of popup : 
![image](https://user-images.githubusercontent.com/2004769/64168207-ea904e80-ce42-11e9-80f8-50f064bb42a3.png)
make no changes and click on save : 
![image](https://user-images.githubusercontent.com/2004769/64168396-54105d00-ce43-11e9-90ed-ff079014900a.png)
or add a new entry and all but the new entry is removed : 
![image](https://user-images.githubusercontent.com/2004769/64168537-ab163200-ce43-11e9-827c-4a569d8bfd9e.png)

**Comment by LoveIsGrief** [comment]
Ah, ok, I could reproduce your first scenario, but I believe the second is how it should work - you are replacing all rules. I'll fix the first one and let @kintesh decide on what the second should do.

**Comment by LoveIsGrief** [comment]
Looking at the code, the second scenario always happened because of `Storage.clear`. That isn't new behavior

**Comment by barneycg** [comment]
Ok you say it always happened but I think I must not have been clear with my description as it doesnt in 3.2.0 as seen here
Before :  
![image](https://user-images.githubusercontent.com/2004769/64189179-ab2a2800-ce6b-11e9-90b3-cd951667e865.png)
During (entered but not hit save) : 
![image](https://user-images.githubusercontent.com/2004769/64189272-d44ab880-ce6b-11e9-8545-2fbe38484099.png)
after (hit save) : 
![image](https://user-images.githubusercontent.com/2004769/64189330-ed536980-ce6b-11e9-8d02-f88564b0c51f.png)

See all the rules including the new one are present.

**Comment by LoveIsGrief** [comment]
Oh, I misunderstood your second scenario. I thought you replaced the whole input with one line and expected that to be added.

#86 should then fix both scenarios:

1. open CSV editor with existing input --> hit save --> everything stays the same
2. open CSV editor with existing input --> add a line --> old rules stay intact and a new one is added

**Comment by kintesh** [comment]
Thanks to @LoveIsGrief this is now fixed in v3.4.0
