### ISSUE TITLE
Endless loop between container and no container since 3.4.0

### ISSUE THREAD

**Issue by OdinGitDat** [kintesh/containerise#89]
I have my rules set up where some domains are sent to specific containers, everything that doesn't match a rule is opened without a container, e.g:
```
@.* , No Container
@.*(\.|\/)facebook\..*$ , Facebook
@.*(\.|\/)google\..*$ , Google
```
Now if I open a link from within a google or fb container it used to just open it outside any container. Since 3.4.0 update it goes into a loop where it switches back and forth endlessly. 

Opening a fb link from within a google container still works as expected. So container to container is fine.

3.3.0 works fine.

**Comment by OdinGitDat** [comment]
I noticed containerise also updated today (sep 4), so maybe that's when the problem started.

**Comment by Colorfag** [comment]
I've been having the same issue as well today. Took me a bit to figure out it was containerise causing it.

**Comment by seascape** [comment]
Containerise caused a similar issue maybe two months ago so it was my first suspect, so to speak. Glad to see it confirmed here, thank you.

**Comment by mrtootoo** [comment]
I currently have the same issue.  I did not realize it was only happening with sites assigned to No Container until reading this thread.  If I right click the link and select No Container to open in, the link opens as expected.  But if I left click the link, say from within the Email container, the click opens a flickering endless loop tab.  I see above issue is closed, did I miss the fix?

**Comment by LoveIsGrief** [comment]
Nothing has been closed yet. We're waiting for the fix to be merged and released.

**Comment by mrtootoo** [comment]
> Nothing has been closed yet. We're waiting for the fix to be merged and released.

I still experience an endless loop between container and no container when left clicking on a link assigned to "No container".  I probably don't understand this thread, but has a fix been released or still in the works?

**Comment by LoveIsGrief** [comment]
A new version exists, but it doesn't seem to have been released. Gotta wait on @kintesh to do so.
