### ISSUE TITLE
Support internationalized domain names

### ISSUE THREAD

**Issue by shvchk** [kintesh/containerise#9]
Now [internationalized domain names](https://en.wikipedia.org/wiki/Internationalized_domain_name) like `тест.рф` are ignored and have to be converted to [punycode](https://en.wikipedia.org/wiki/Punycode) (`тест.рф` → `xn--e1aybc.xn--p1ai`) to work. As punycode is not human-readable, it is very easy to make a mistake adding or changing such domains. Would be nice to be able to add and list domains in Unicode instead of punycode.

[punycode.js](https://github.com/bestiejs/punycode.js) might be of help.

**Comment by LoveIsGrief** [comment]
I wouldn't mind having a look at this, but do you have an example @shvchk ?

**Comment by shvchk** [comment]
@LoveIsGrief [карелия.рф](http://карелия.рф) or [мосполитех.рф](http://мосполитех.рф) or [лигагероев.укр](http://лигагероев.укр)

**Comment by LoveIsGrief** [comment]
This should've been fixed with #48

Could you confirm @shvchk ?

I'll reopen if that's not the case.
