### ISSUE TITLE
"Keep old tabs" should not keep useless tabs (new tab page, temp tabs)

### ISSUE THREAD

**Issue by kristofferR** [kintesh/containerise#93]
The "Keep old tabs" functionality is super confusing. It works as it says, but I'd like it to work more intelligently. Zombie temp tabs are left when links are ctrl-clicked. If I open a new empty tab and enter a containerized site it opens a new tab with the page, but still keeps the old useless new tab page. 

If I enter a new URL in the address bar, it just opens a new tab with that page instead of replacing the current one.

I'd much rather have it work like this:
- Empty New tab pages should not be kept
- Temp tabs redirected to a new container should not be kept
- Manually input URLs should overwrite the current site

Here's a video of the first two issues:
https://streamable.com/0etkx

**Comment by LoveIsGrief** [comment]
It came from #14 . I honestly didn't think it was a good idea, hence the preference and not default behavior. Personally, I won't be working on this directly. The next big feature (after default containers) will be exit rules for containers which might include this.

PRs are welcome though.

**Comment by go2null** [comment]
this is what prevents me from using the *Keep old tabs* option - as it lead to too much manual cleaning up.

**Comment by switz** [comment]
Yeah, this is relatively easily fixable UX. I'm happy to implement this if we get confirmation it'll be merged.

**Comment by muzzah** [comment]
@switz I also experience this but Im not sure your change will fix it. I have the default container option enabled and also regex to open google domain in a separate google container. If I am on a google container and then click on a link (which does not match any regex i have setup thus should open a default container linked tab) that opens a new tab, that new tab is still linked to the google container and then when it goes to load the actual (non google) link, it spawns another tab which loads the page but that initial tab it it opened is still there with a google link.

So lets say I visit google shopping (in google container), find an item and click visit site, I end up with 3 tabs, 1 google shopping (google container), 1 google redirect link (Google container with google redirect url but is a blank page), 1 actual website (Default container).

**Comment by switz** [comment]
I don't use a default container so that may be an edge case that this doesn't solve.

What is the google redirect page URL? After that intermediate tab is created, open your developer console and type `window.location.href`. What url is it actually?

**Comment by muzzah** [comment]
When you click the visit site link, it opens a URL in the form of "https://www.google.com/aclk?sa...." in a new tab (So google shopping uses _blank type attribute) as to keep the shopping website open. This then redirects to a new URL which opens in a new default container tab.

You can go to the shopping.google.com website, search for a then click on the visit site link for that product to replicate.

**Comment by muzzah** [comment]
ok interesting to note, when I do use the console to check the value you mention, it shows about:blank

**Comment by switz** [comment]
Great! It should work flawlessly for you then; that's the same as me.
