### ISSUE TITLE
Waterfox + Containerise = undefined

### ISSUE THREAD

**Issue by tomose** [kintesh/containerise#95]
https://imgur.com/baiBVNh

Yes, Waterfox, not Firefox.

First thing I did was attempt to install containerise. But no matter what version I grab it's always undefined.

I notice now in my current profile which still has it working, that I am unable to customize categories anymore.

If this is something inherent to WF that is unfixable on your end, I will understand and seek out the WF dev. But all other plugins seem to be functioning so maybe it's just an oversight with the containerise plugin?

**Comment by LoveIsGrief** [comment]
1. Does Waterfox support containers?

2. Does waterfox also have a browser console (Ctrl+Shift+J)? It might be throwing an exception which can be seen there.

I'm just a contributor, but I doubt support for anything but firefox can be provided at the time. If someone in the community has the time, they are welcome to take a shot at this

**Comment by tomose** [comment]
> 
> 
>     1. Does Waterfox support containers?
> 
>     2. Does waterfox also have a browser console (Ctrl+Shift+J)? It might be throwing an exception which can be seen there.
> 
> 
> I'm just a contributor, but I doubt support for anything but firefox can be provided at the time. If someone in the community has the time, they are welcome to take a shot at this

https://imgur.com/a/iLhcMdT

**Comment by LoveIsGrief** [comment]
Waterfox doesn't support containers or doesn't have an API for it seems. This extension won't work with it. Sorry.

**Comment by tomose** [comment]
@LoveIsGrief 

Found this: https://www.reddit.com/r/waterfox/comments/aj5cin/multiaccount_container_addon_incompatible_with/eri5tg5/

Seems to have resolved the lack of config options in preferences and now Containerise seems to work on a new profile.
